In [1]:
import pandas as pd
import numpy as np
import copy
import warnings
warnings.filterwarnings(action='ignore')

In [2]:
file = 'C:/Users/0630r/inha2/Research/Dart/Dart_file/support_data/dart-2020-2022.xlsx'
df2 = pd.read_excel(file, sheet_name = [3], header = 2)
df3 = pd.read_excel(file, sheet_name = [4], header = 2)
df4 = pd.read_excel(file, sheet_name = [5], header = 2)

## 2020년 Market 정리

In [3]:
df2 = df2[3]

def start(df):
    df = df.transpose() # 행열 변환
    df.drop([0,1], axis = 1, inplace = True) # 필요없는 열 삭제
    df = df.rename(columns = df.iloc[0,:]) # 1행을 열로 올림
    df = df.drop(df.index[0]) # 원래 1행 삭제
    df.columns = df.columns.astype('string')
    return df

df2 = start(df2)
df2.to_parquet('orign_market20.pqt') # 20년도 저장
df2.head()

,2020-01-02,2020-01-03,2020-01-06,2020-01-07,2020-01-08,2020-01-09,2020-01-10,2020-01-13,2020-01-14,2020-01-15,...,2020-12-16,2020-12-17,2020-12-18,2020-12-21,2020-12-22,2020-12-23,2020-12-24,2020-12-28,2020-12-29,2020-12-30
KRX:000020:동화약품,234624348000,233507089200,228479424600,227920795200,221496557100,220658613000,226244907000,229596683400,227362165800,225965592300,...,536284224000,527904783000,571198561500,654992971500,667562133000,571198561500,558629400000,520921915500,534887650500,548853385500
.1,8400,8360,8180,8160,7930,7900,8100,8220,8140,8090,...,19200,18900,20450,23450,23900,20450,20000,18650,19150,19650
KRX:000040:KR모터스,53423229150,52854896925,51718232475,50202679875,49444903575,50771012100,52854896925,53612673225,53612673225,52665452850,...,108160001240,104951865610,112284747050,111368136870,102660340160,102202035070,99452204530,94869153630,98535594350,104035255430
.2,1145,1133,1108,1076,1060,1088,1133,1149,1149,1129,...,1180,1145,1225,1215,1120,1115,1085,1035,1075,1135
KRX:000050:경방,262638286600,262912439300,261541675800,262089981200,254139552900,256058621800,256881079900,256606927200,256606927200,258525996100,...,326241713000,328983240000,330354003500,331724767000,327612476500,328983240000,330354003500,331724767000,337207821000,339949348000

In [4]:
path = 'C:/Users/0630r/inha2/Research/Dart/Dart_file/real_code/pqt_file/'
df2 = pd.read_parquet(path+'orign_market20.pqt')
df2.head()

,2020-01-02,2020-01-03,2020-01-06,2020-01-07,2020-01-08,2020-01-09,2020-01-10,2020-01-13,2020-01-14,2020-01-15,...,2020-12-16,2020-12-17,2020-12-18,2020-12-21,2020-12-22,2020-12-23,2020-12-24,2020-12-28,2020-12-29,2020-12-30
KRX:000020:동화약품,234624348000,233507089200,228479424600,227920795200,221496557100,220658613000,226244907000,229596683400,227362165800,225965592300,...,536284224000,527904783000,571198561500,654992971500,667562133000,571198561500,558629400000,520921915500,534887650500,548853385500
.1,8400,8360,8180,8160,7930,7900,8100,8220,8140,8090,...,19200,18900,20450,23450,23900,20450,20000,18650,19150,19650
KRX:000040:KR모터스,53423229150,52854896925,51718232475,50202679875,49444903575,50771012100,52854896925,53612673225,53612673225,52665452850,...,108160001240,104951865610,112284747050,111368136870,102660340160,102202035070,99452204530,94869153630,98535594350,104035255430
.2,1145,1133,1108,1076,1060,1088,1133,1149,1149,1129,...,1180,1145,1225,1215,1120,1115,1085,1035,1075,1135
KRX:000050:경방,262638286600,262912439300,261541675800,262089981200,254139552900,256058621800,256881079900,256606927200,256606927200,258525996100,...,326241713000,328983240000,330354003500,331724767000,327612476500,328983240000,330354003500,331724767000,337207821000,339949348000

In [5]:
# 분기별 데이터 subset
df20_1Q = df2.loc[:, :'2020-03-31']
df20_2Q = df2.loc[:, '2020-04-01':'2020-06-30']
df20_3Q = df2.loc[:, '2020-07-01':'2020-09-30']
df20_4Q = df2.loc[:, '2020-10-01':'2020-12-31']

In [6]:
df20_1Q.head(6)
# (시가총액 , 종가) | (시가총액,  종가) 로 이루어져있음

,2020-01-02,2020-01-03,2020-01-06,2020-01-07,2020-01-08,2020-01-09,2020-01-10,2020-01-13,2020-01-14,2020-01-15,...,2020-03-18,2020-03-19,2020-03-20,2020-03-23,2020-03-24,2020-03-25,2020-03-26,2020-03-27,2020-03-30,2020-03-31
KRX:000020:동화약품,234624348000,233507089200,228479424600,227920795200,221496557100,220658613000,226244907000,229596683400,227362165800,225965592300,...,151388567400,139238377950,144964329300,140215979400,148874735100,157254176100,164795673000,171219911100,177364834500,182951128500
.1,8400,8360,8180,8160,7930,7900,8100,8220,8140,8090,...,5420,4985,5190,5020,5330,5630,5900,6130,6350,6550
KRX:000040:KR모터스,53423229150,52854896925,51718232475,50202679875,49444903575,50771012100,52854896925,53612673225,53612673225,52665452850,...,26001198882,20886208938,22780649658,21643985226,23064815766,25906476846,27800917566,28132444692,28227166728,28369249782
.2,1145,1133,1108,1076,1060,1088,1133,1149,1149,1129,...,549,441,481,457,487,547,587,594,596,599
KRX:000050:경방,262638286600,262912439300,261541675800,262089981200,254139552900,256058621800,256881079900,256606927200,256606927200,258525996100,...,239883612500,197664096700,199583165600,187794599500,192729348100,201228081800,209178510100,199034860200,207259441200,213290800600
.3,9580,9590,9540,9560,9270,9340,9370,9360,9360,9430,...,8750,7210,7280,6850,7030,7340,7630,7260,7560,7780

In [7]:
# 시가총액, 주가 평균 정리
def Mean(df):
    df_시총 = df[::2] # 시가총액 추출
    df_시총['시가총액'] = round(df_시총[df.columns].sum(axis = 1)/len(df.columns)) # 시가 총액 평균 
    df_주가 = df[1::2] # 주가 추출
    df_주가['주가평균'] = round(df_주가[df.columns].sum(axis = 1)/len(df.columns)) # 종가 평균
    df_주가.set_index(df_시총.index, inplace = True) # 인덱스를 기업 이름으로 정렬
    df1 = pd.concat([df_시총,df_주가], axis = 1) # concat
    df1 = df1[['시가총액', '주가평균']]
    return df1

# 데이터 합병 및 정리
def clean(df1,df2,df3,df4):
    df20 = pd.concat([df1, df2, df3, df4], axis = 0) # 전체 concat
    df20 = df20[['분기', '시가총액', '주가평균']] # 
    df20.reset_index(inplace = True) # 인덱스 추가
    df20.rename(columns = {'index': '회사명'}, inplace = True) # 회사명 열 생성
    df20.sort_values(by=['회사명','분기'], inplace = True) # 회사와 분기별로 정렬
    df20.reset_index(drop = True, inplace = True)
    return df20

In [8]:
df1Q = Mean(df20_1Q)
df1Q['분기'] = '1Q'
df2Q = Mean(df20_2Q)
df2Q['분기'] = '2Q'
df3Q = Mean(df20_3Q)
df3Q['분기'] = '3Q'
df4Q = Mean(df20_4Q)
df4Q['분기'] = '4Q'

df20 = clean(df1Q, df2Q, df3Q, df4Q)
df20.insert(1,'연도', 2020) # 2020 년도 추가
df20.drop(df20[df20['시가총액'] == 0].index, inplace = True) # 시가총액 0인 분기 삭제 
df20

                   회사명    연도  분기          시가총액     주가평균
0      KRX:000020:동화약품  2020  1Q  2.015323e+11   7215.0
1      KRX:000020:동화약품  2020  2Q  3.231671e+11  11570.0
2      KRX:000020:동화약품  2020  3Q  6.211042e+11  22237.0
3      KRX:000020:동화약품  2020  4Q  5.538673e+11  19830.0
4     KRX:000040:KR모터스  2020  1Q  4.000326e+10    853.0
...                ...   ...  ..           ...      ...
8879    KRX:950170:JTC  2020  4Q  1.722099e+11   4920.0
8882    KRX:950190:미투젠  2020  3Q  1.858921e+11  14422.0
8883    KRX:950190:미투젠  2020  4Q  3.521711e+11  27322.0
8886    KRX:950200:소마젠  2020  3Q  2.486488e+11  14693.0
8887    KRX:950200:소마젠  2020  4Q  3.107363e+11  16418.0

[8698 rows x 5 columns]

## 2021년 Market 정리

In [9]:
df3 = df3[4]
df3 = start(df3)
df3.to_parquet('orign_market21.pqt') # 21년도 저장
df3.head()

,2021-01-04,2021-01-05,2021-01-06,2021-01-07,2021-01-08,2021-01-11,2021-01-12,2021-01-13,2021-01-14,2021-01-15,...,2021-12-17,2021-12-20,2021-12-21,2021-12-22,2021-12-23,2021-12-24,2021-12-27,2021-12-28,2021-12-29,2021-12-30
KRX:000020:동화약품,533491077000,541870518000,550249959000,550249959000,533491077000,505559607000,505559607000,502766460000,515335621500,504163033500,...,431541211500,411989182500,402213168000,416178903000,409196035500,403609741500,416178903000,405006315000,411989182500,407799462000
.1,19100,19400,19700,19700,19100,18100,18100,18000,18450,18050,...,15450,14750,14400,14900,14650,14450,14900,14500,14750,14600
KRX:000040:KR모터스,105410170700,103118645250,101285424890,102660340160,102202035070,98077289260,95327458720,100827119800,98077289260,96702373990,...,84793158576,84120197000,84312471736,83158823320,82678136480,83543372792,83639510160,83158823320,83254960688,83158823320
.2,1150,1125,1105,1120,1115,1070,1040,1100,1070,1055,...,882,875,877,865,860,869,870,865,866,865
KRX:000050:경방,337207821000,337207821000,342690875000,356398510000,353656983000,338578584500,344061638500,357769273500,346803165500,356398510000,...,374218435500,370106145000,372847672000,375589199000,378330726000,378330726000,375589199000,375589199000,374218435500,376959962500

In [10]:
df3 = pd.read_parquet(path+'orign_market21.pqt', engine = 'pyarrow')

# 분기별로 정렬
df21_1Q = df3.loc[:, :'2021-03-31']
df21_2Q = df3.loc[:, '2021-04-01':'2021-06-30']
df21_3Q = df3.loc[:, '2021-07-01':'2021-09-30']
df21_4Q = df3.loc[:, '2021-10-01':'2021-12-31']

In [11]:
df1Q = Mean(df21_1Q)
df1Q['분기'] = '1Q'
df2Q = Mean(df21_2Q)
df2Q['분기'] = '2Q'
df3Q = Mean(df21_3Q)
df3Q['분기'] = '3Q'
df4Q = Mean(df21_4Q)
df4Q['분기'] = '4Q'

df21 = clean(df1Q, df2Q, df3Q, df4Q)
df21.insert(1,'연도', 2021)
df21.drop(df21[df21['시가총액'] == 0].index, inplace = True) # 시가총액 0인 분기 삭제 
df21

                        회사명    연도  분기          시가총액     주가평균
0           KRX:000020:동화약품  2021  1Q  4.390362e+11  15718.0
1           KRX:000020:동화약품  2021  2Q  4.181075e+11  14969.0
2           KRX:000020:동화약품  2021  3Q  4.273515e+11  15300.0
3           KRX:000020:동화약품  2021  4Q  4.332703e+11  15512.0
4          KRX:000040:KR모터스  2021  1Q  1.129259e+11   1190.0
...                     ...   ...  ..           ...      ...
9347  KRX:950210:프레스티지바이오파마  2021  4Q  1.430527e+12  23804.0
9348       KRX:950220:네오이뮨텍  2021  1Q  2.678722e+11   2722.0
9349       KRX:950220:네오이뮨텍  2021  2Q  1.156965e+12  11759.0
9350       KRX:950220:네오이뮨텍  2021  3Q  1.009057e+12  10255.0
9351       KRX:950220:네오이뮨텍  2021  4Q  1.028421e+12  10438.0

[9172 rows x 5 columns]

## 2022년 Market 정리

In [12]:
df4 = df4[5]
df4 = start(df4)
df4.to_parquet('orign_market22.pqt') # 22년도 저장
df4.head()

,2022-01-03,2022-01-04,2022-01-05,2022-01-06,2022-01-07,2022-01-10,2022-01-11,2022-01-12,2022-01-13,2022-01-14,...,2022-12-16,2022-12-19,2022-12-20,2022-12-21,2022-12-22,2022-12-23,2022-12-26,2022-12-27,2022-12-28,2022-12-29
KRX:000020:동화약품,417575476500,416178903000,406402888500,398023447500,407799462000,407799462000,400816594500,400816594500,393833727000,386850859500,...,278476755900,269818000200,262555818000,274845664800,273169776600,267583482600,269818000200,268421426700,265907594400,258645412200
.1,14950,14900,14550,14250,14600,14600,14350,14350,14100,13850,...,9970,9660,9400,9840,9780,9580,9660,9610,9520,9260
KRX:000040:KR모터스,84216334368,86427493832,88157966456,87004318040,87100455408,83447235424,82870411216,83543372792,83543372792,83543372792,...,54798925050,54125955795,52683878820,52972294215,52972294215,52876155750,53164571145,53837540400,54029817330,53837540400
.2,876,899,917,905,906,868,862,869,869,869,...,570,563,548,551,551,550,553,560,562,560
KRX:000050:경방,376959962500,385184543500,386555307000,387926070500,387926070500,390667597500,392038361000,396150651500,397521415000,401633705500,...,311163314500,311163314500,308421787500,311163314500,311163314500,301567970000,305680260500,301567970000,304309497000,296084916000

In [13]:
df4 = pd.read_parquet(path+'orign_market22.pqt', engine = 'pyarrow')

# 분기별 저장
df22_1Q = df4.loc[:, :'2022-03-31']
df22_2Q = df4.loc[:, '2022-04-01':'2022-06-30']
df22_3Q = df4.loc[:, '2022-07-01':'2022-09-30']
df22_4Q = df4.loc[:, '2022-10-01':'2022-12-31']

In [14]:
df1Q = Mean(df22_1Q)
df1Q['분기'] = '1Q'
df2Q = Mean(df22_2Q)
df2Q['분기'] = '2Q'
df3Q = Mean(df22_3Q)
df3Q['분기'] = '3Q'
df4Q = Mean(df22_4Q)                                        
df4Q['분기'] = '4Q'

df22 = clean(df1Q, df2Q, df3Q, df4Q)
df22.insert(1,'연도', 2022)
df22.drop(df22[df22['시가총액'] == 0].index, inplace = True) # 시가총액 0인 분기 삭제 
df22

                   회사명    연도  분기          시가총액     주가평균
0      KRX:000020:동화약품  2022  1Q  3.662573e+11  13113.0
1      KRX:000020:동화약품  2022  2Q  3.286903e+11  11768.0
2      KRX:000020:동화약품  2022  3Q  2.804896e+11  10042.0
3      KRX:000020:동화약품  2022  4Q  2.561316e+11   9170.0
4     KRX:000040:KR모터스  2022  1Q  7.927911e+10    825.0
...                ...   ...  ..           ...      ...
9511    KRX:403360:라피치  2022  4Q  3.467001e+10  11939.0
9514     KRX:403550:쏘카  2022  3Q  3.125040e+11   9549.0
9515     KRX:403550:쏘카  2022  4Q  6.145033e+11  18777.0
9518   KRX:403870:HPSP  2022  3Q  9.995065e+11  50467.0
9519   KRX:403870:HPSP  2022  4Q  1.181459e+12  59016.0

[9414 rows x 5 columns]

In [15]:
# 데이터 병합 및 정렬
df_tt = pd.concat([df20, df21, df22], axis = 0)
df_tt.sort_values(by=['회사명','연도','분기'], inplace = True)
df_tt.reset_index(drop=True, inplace = True)
df_tt.to_parquet('market_final.pqt')
# 완

In [ ]:
## orign_market20, orign_market21, orign_market22, market_final 4개 저장